# Generated by Django 6.0.2 on 2026-03-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpvapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='color_boton',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='impresora',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre_comanda',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre_factura',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
