# Generated by Django 6.0.2 on 2026-03-05 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpvapp', '0002_producto_color_boton_producto_impresora_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilComentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Perfil de Comentarios',
                'verbose_name_plural': 'Perfiles de Comentarios',
                'db_table': 'grupo_comentarios',
            },
        ),
        migrations.CreateModel(
            name='PerfilSuplementos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Perfil de Suplementos',
                'verbose_name_plural': 'Perfiles de Suplementos',
                'db_table': 'grupo_suplementos',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
                ('perfil', models.ForeignKey(blank=True, db_column='grupo_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='tpvapp.perfilcomentarios')),
            ],
            options={
                'db_table': 'comentarios',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='perfiles_comentarios',
            field=models.ManyToManyField(blank=True, related_name='departamentos', to='tpvapp.perfilcomentarios'),
        ),
        migrations.AddField(
            model_name='producto',
            name='perfiles_comentarios',
            field=models.ManyToManyField(blank=True, db_table='producto_grupo_comentario', related_name='productos', to='tpvapp.perfilcomentarios'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='perfiles_suplementos',
            field=models.ManyToManyField(blank=True, related_name='departamentos', to='tpvapp.perfilsuplementos'),
        ),
        migrations.AddField(
            model_name='producto',
            name='perfiles_suplementos',
            field=models.ManyToManyField(blank=True, db_table='producto_grupo_suplemento', related_name='productos', to='tpvapp.perfilsuplementos'),
        ),
        migrations.CreateModel(
            name='Suplemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
                ('perfil', models.ForeignKey(blank=True, db_column='grupo_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suplementos', to='tpvapp.perfilsuplementos')),
            ],
            options={
                'db_table': 'suplementos',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
