# Generated by Django 6.0.2 on 2026-03-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpvapp', '0003_perfilcomentarios_perfilsuplementos_comentario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='color_texto',
            field=models.CharField(blank=True, default='#ffffff', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='icono_boton',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
