# Generated by Django 6.0.2 on 2026-03-10 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpvapp', '0004_producto_color_texto_producto_icono_boton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='perfil',
            field=models.ForeignKey(blank=True, db_column='grupo_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comentarios', to='tpvapp.perfilcomentarios'),
        ),
        migrations.AlterField(
            model_name='suplemento',
            name='perfil',
            field=models.ForeignKey(blank=True, db_column='grupo_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suplementos', to='tpvapp.perfilsuplementos'),
        ),
    ]
