# Generated by Django 6.0.2 on 2026-03-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpvapp', '0005_alter_comentario_perfil_alter_suplemento_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cambio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='factura',
            name='efectivo_entregado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
