# Generated by Django 6.0.2 on 2026-03-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpvapp', '0006_factura_cambio_factura_efectivo_entregado'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineacomanda',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
