# Generated by Django 6.0.2 on 2026-03-17 12:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpvapp', '0007_lineacomanda_descuento'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('efectivo_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_ventas_efectivo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_ventas_tarjeta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('efectivo_final_real', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('abierta_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_abiertas', to=settings.AUTH_USER_MODEL)),
                ('cerrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_cerradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sesiones_caja',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concepto', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='tpvapp.sesioncaja')),
            ],
            options={
                'db_table': 'movimientos_caja',
                'ordering': ['-fecha'],
            },
        ),
    ]
