# Generated by Django 6.0.2 on 2026-03-17 12:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpvapp', '0008_sesioncaja_movimientocaja'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionTPV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50, unique=True)),
                ('valor', models.TextField()),
                ('descripcion', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'configuracion_tpv',
            },
        ),
        migrations.CreateModel(
            name='DiaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('abierta_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dias_abiertos', to=settings.AUTH_USER_MODEL)),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dias_cerrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dias_contables',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='dia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='tpvapp.diacontable'),
            preserve_default=False,
        ),
    ]
