# Generated by Django 6.0.2 on 2026-03-17 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpvapp', '0009_configuraciontpv_diacontable_sesioncaja_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesioncaja',
            name='dia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='tpvapp.diacontable'),
        ),
    ]
