# Generated by Django 6.0.2 on 2026-03-20 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpvapp', '0010_alter_sesioncaja_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='tpvapp.sesioncaja'),
        ),
        migrations.AddField(
            model_name='pago',
            name='sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='tpvapp.sesioncaja'),
        ),
    ]
