# Generated by Django 6.0.2 on 2026-03-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpvapp', '0012_cliente_comanda_cliente_factura_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='poblacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Población / Ciudad'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='factura',
            name='email_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Domicilio Fiscal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nif',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NIF/CIF/NIE'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre / Razón Social'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
    ]
