# Generated by Django 6.0.2 on 2026-03-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpvapp', '0013_cliente_codigo_postal_cliente_poblacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='icono_boton',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
