# Generated by Django 6.0.2 on 2026-04-06 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpvapp', '0014_alter_producto_icono_boton'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoOpciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_seleccion', models.CharField(choices=[('unica', 'Única'), ('multiple', 'Múltiple')], default='multiple', max_length=10)),
                ('obligatorio', models.BooleanField(default=False)),
                ('permite_texto_libre', models.BooleanField(default=False)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'grupos_opciones',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddField(
            model_name='lineacomanda',
            name='configuracion_json',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='es_configurable',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OpcionGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='tpvapp.grupoopciones')),
            ],
            options={
                'db_table': 'opciones_grupo',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaConfigurable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiene_formatos', models.BooleanField(default=False)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plantilla', to='tpvapp.producto')),
            ],
            options={
                'db_table': 'plantillas_configurables',
            },
        ),
        migrations.AddField(
            model_name='grupoopciones',
            name='plantilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='tpvapp.plantillaconfigurable'),
        ),
        migrations.CreateModel(
            name='FormatoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('factor_precio', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('precio_fijo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('por_defecto', models.BooleanField(default=False)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formatos', to='tpvapp.plantillaconfigurable')),
            ],
            options={
                'db_table': 'formatos_producto',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PrecioOpcionFormato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('formato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_opciones', to='tpvapp.formatoproducto')),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_formato', to='tpvapp.opciongrupo')),
            ],
            options={
                'db_table': 'precios_opcion_formato',
                'unique_together': {('opcion', 'formato')},
            },
        ),
    ]
