# Generated by Django 6.0.2 on 2026-04-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpvapp', '0015_grupoopciones_lineacomanda_configuracion_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opciongrupo',
            name='por_defecto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opciongrupo',
            name='visible_comanda',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='opciongrupo',
            name='visible_factura',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='grupoopciones',
            name='tipo_seleccion',
            field=models.CharField(choices=[('unica', 'Única'), ('multiple', 'Múltiple'), ('libre', 'Texto Libre')], default='multiple', max_length=10),
        ),
    ]
