# Generated by Django 6.0.2 on 2026-04-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpvapp', '0016_opciongrupo_por_defecto_opciongrupo_visible_comanda_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impresora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('barra', 'Barra'), ('cocina', 'Cocina'), ('caja', 'Caja / Tickets'), ('otra', 'Otra')], default='caja', max_length=20)),
                ('ip_o_puerto', models.CharField(blank=True, help_text='IP (ej: 192.168.1.50) o Puerto (ej: COM1, USB0)', max_length=100, null=True)),
                ('papel_mm', models.IntegerField(default=80, help_text='Ancho de papel en mm (58 o 80)')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Impresora',
                'verbose_name_plural': 'Impresoras',
                'db_table': 'impresoras',
            },
        ),
    ]
