# Generated by Django 6.0.2 on 2026-04-14 10:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpvapp', '0017_impresora'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada (Compra/Reposición)'), ('salida', 'Salida (Mermas/Roturas)'), ('venta', 'Venta (Automático)'), ('ajuste', 'Ajuste de Inventario'), ('anulad', 'Anulación de Venta')], max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nuevo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('linea_comanda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to='tpvapp.lineacomanda')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_stock', to='tpvapp.producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'movimientos_stock',
                'ordering': ['-fecha'],
            },
        ),
    ]
