# Generated by Django 6.0.2 on 2026-04-16 09:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpvapp', '0018_formatoproducto_unidades_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría de Inventario',
                'verbose_name_plural': 'Categorías de Inventario',
                'db_table': 'categorias_inventario',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AlterField(
            model_name='movimientostock',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_stock', to='tpvapp.producto'),
        ),
        migrations.CreateModel(
            name='ArticuloInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('unidad', models.CharField(choices=[('ud', 'Unidades'), ('pack', 'Packs'), ('caja', 'Cajas'), ('kg', 'Kilos'), ('g', 'Gramos'), ('l', 'Litros'), ('ml', 'Mililitros')], default='ud', max_length=5)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('auto_descontar', models.BooleanField(default=False, help_text='Si está activo, se descuenta stock automáticamente al vender el producto vinculado', verbose_name='Descontar al vender')),
                ('cantidad_por_venta', models.DecimalField(decimal_places=2, default=1, help_text='Unidades que se descuentan por cada venta del producto vinculado', max_digits=10, verbose_name='Cantidad por venta')),
                ('proveedor', models.CharField(blank=True, default='', max_length=150)),
                ('precio_compra', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio de compra por unidad')),
                ('notas', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('producto_vinculado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulo_inventario', to='tpvapp.producto')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos', to='tpvapp.categoriainventario')),
            ],
            options={
                'verbose_name': 'Artículo de Inventario',
                'verbose_name_plural': 'Artículos de Inventario',
                'db_table': 'articulos_inventario',
                'ordering': ['categoria__orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='articulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='tpvapp.articuloinventario'),
        ),
    ]
