# Generated by Django 6.0.2 on 2026-04-20 09:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpvapp', '0019_categoriainventario_alter_movimientostock_producto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('INFO', 'Información'), ('WARN', 'Advertencia'), ('ERROR', 'Error'), ('CRITICAL', 'Crítico')], default='INFO', max_length=10)),
                ('origen', models.CharField(help_text='Módulo o sección que generó el log', max_length=100)),
                ('mensaje', models.TextField()),
                ('traza', models.TextField(blank=True, default='', help_text='Stack trace (si aplica)')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Log del Sistema',
                'verbose_name_plural': 'Logs del Sistema',
                'db_table': 'logs_sistema',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='BackupRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('ruta', models.CharField(help_text='Ruta relativa dentro de media/backups/', max_length=500)),
                ('tamano_bytes', models.BigIntegerField(default=0)),
                ('tipo', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Automático')], default='manual', max_length=10)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('notas', models.TextField(blank=True, default='')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup',
                'verbose_name_plural': 'Backups',
                'db_table': 'backup_registros',
                'ordering': ['-fecha'],
            },
        ),
    ]
