# Generated by Django 6.0.2 on 2026-05-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpvapp', '0024_permisos_fk_set_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_system_user',
            field=models.BooleanField(default=False, editable=False, help_text='Usuario de sistema creado automáticamente. No puede eliminarse ni renombrarse.'),
        ),
    ]
