# Generated by Django 6.0.2 on 2026-05-07 11:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpvapp', '0025_alter_usuario_is_system_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('albaran', 'Albaran'), ('factura', 'Factura')], max_length=12)),
                ('proveedor_nombre', models.CharField(blank=True, default='', max_length=150)),
                ('numero', models.CharField(blank=True, default='', max_length=80)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('vencimiento', models.DateField(blank=True, null=True)),
                ('concepto', models.CharField(blank=True, default='', max_length=255)),
                ('base', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('recibido', 'Recibido'), ('contabilizado', 'Contabilizado'), ('pagado', 'Pagado')], default='pendiente', max_length=20)),
                ('notas', models.TextField(blank=True, default='')),
                ('creado_a', models.DateTimeField(default=django.utils.timezone.now)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_proveedor_creados', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='tpvapp.proveedor')),
            ],
            options={
                'verbose_name': 'Documento de proveedor',
                'verbose_name_plural': 'Documentos de proveedor',
                'db_table': 'documentos_proveedor',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
