"""
Django settings for tpv project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import os
from urllib.parse import urlparse

# Lee una variable de entorno y la convierte en booleano (True/False). 
def _env_bool(name: str, default: bool = False) -> bool:
    v = os.environ.get(name)
    # Si la variable no está definida, devuelve el valor por defecto (False si no se especifica).
    if v is None:
        return default
    # Considera como "True" los valores: "1", "true", "yes", "y", "on" (sin importar mayúsculas).
    return v.strip().lower() in {"1", "true", "yes", "y", "on"}

# Lee una variable de entorno y la convierte en una lista de strings, separando por comas.
def _env_list(name: str, default=None):
    # Si la variable no está definida o está vacía, devuelve el valor por defecto (lista vacía si no se especifica).
    if default is None:
        default = []
    v = os.environ.get(name)
    if not v:
        return default
    # Elimina espacios en blanco alrededor de cada elemento y omite los elementos vacíos.
    return [x.strip() for x in v.split(",") if x.strip()]

# Lee una URL de base de datos y la convierte en un diccionario de configuración para Django.
def _database_from_url(database_url: str):
    """Minimal DATABASE_URL parser.

    Supports:
      - sqlite:///path/to/db.sqlite3
      - mysql://USER:PASSWORD@HOST:PORT/DBNAME
      - postgres:// ... (left here for future, but not required)
    """
    # Analiza el esquema de la URL para determinar el tipo de base de datos (sqlite, mysql, postgres).
    p = urlparse(database_url)
    scheme = (p.scheme or "").lower()

    # Para cada tipo de base de datos, extrae los componentes necesarios (nombre, usuario, contraseña, host, puerto) 
    # y devuelve un diccionario con la configuración adecuada para Django.
    if scheme in {"sqlite", "sqlite3"}:
        # sqlite:////absolute/path or sqlite:///relative/path
        path = p.path
        if not path:
            raise ValueError("Invalid sqlite DATABASE_URL")
        return {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": path,
        }

    if scheme in {"mysql"}:
        return {
            "ENGINE": "django.db.backends.mysql",
            "NAME": (p.path or "").lstrip("/"),
            "USER": p.username or "",
            "PASSWORD": p.password or "",
            "HOST": p.hostname or "",
            "PORT": str(p.port or 3306),
            "OPTIONS": {"charset": "utf8mb4"},
        }

    if scheme in {"postgres", "postgresql"}:
        return {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": (p.path or "").lstrip("/"),
            "USER": p.username or "",
            "PASSWORD": p.password or "",
            "HOST": p.hostname or "",
            "PORT": str(p.port or 5432),
        }

    # Si el esquema no es reconocido, lanza un error.
    raise ValueError(f"Unsupported DATABASE_URL scheme: {scheme}")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- Carga de variables de entorno desde .env (solo en desarrollo) ---
# En produccion las variables las inyecta el contenedor / Secrets Manager.
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / ".env")
except ImportError:
    # python-dotenv no esta instalado: se asume que las variables ya estan
    # definidas en el entorno (caso tipico en produccion).
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    raise RuntimeError(
        "DJANGO_SECRET_KEY no esta definida. "
        "Copia .env.example a .env y rellena los valores."
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DJANGO_DEBUG", default=False)

ALLOWED_HOSTS = _env_list(
    "DJANGO_ALLOWED_HOSTS",
    default=["127.0.0.1", "localhost"],
)

CSRF_TRUSTED_ORIGINS = _env_list(
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    default=[],
)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'tpvapp.apps.TpvappConfig',
    'ui',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'ui.middleware.AuditActionMiddleware',
    'ui.middleware.SystemErrorLoggingMiddleware',
]

ROOT_URLCONF = 'tpv.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'ui.context_processors.caja_estado',
            ],
        },
    },
]

WSGI_APPLICATION = 'tpv.wsgi.application'

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ]
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = "tpvapp.Usuario"

LOGIN_URL = "ui:login"
LOGIN_REDIRECT_URL = "ui:index"
LOGOUT_REDIRECT_URL = "ui:index"

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es'

LANGUAGES = [
  ("es", "Español"),
  ("en", "English"),
]

LOCALE_PATHS = [BASE_DIR / "locale"]

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

